name: "Next Major"

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  version: nextmajor
  appVersion: '2.0'
  appBuild: 2147483647
  appRevision: 0

defaults:
  run:
    shell: PowerShell

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run pipeline
        env:
          InsiderSasToken: ${{ secrets.InsiderSasToken }}
          LicenseFile: ${{ secrets.LicenseFile }}
        run: scripts\DevOps-Pipeline.ps1 -environment GitHubActions -version ${{env.version}} -appBuild ${{env.appBuild}} -appRevision ${{env.appRevision}}

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'testresults*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: scripts\Cleanup.ps1
      
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.NOTIFICATION_MAIL_ACCOUNT}}
          password: ${{secrets.NOTIFICATION_MAIL_PASSWORD}}
          from: ${{secrets.NOTIFICATION_MAIL_ACCOUNT}}
          to: ${{secrets.NOTIFICATION_MAIL_RECIPIENT}}
          subject: ${{ github.repository }} - ${{github.workflow}} ${{ job.status }}
          body: The ${{github.workflow}} workflow in ${{ github.repository }} completed and the status is ${{ job.status }}.  Details from this automated run can be found here ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
